title: "Nhi Mai-Do"
email: nhi_maido@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Nhi's tech portfolio
# Root directory for your portfolio. On GitHub Pages, this is the name of your repository.
baseurl: "/portfolio-template"
# Protocol + hostname for your portfolio. On GitHub Pages, this is https://yourusername.github.io
url: "https://n-maido.github.io" 
github_username: n-maido
form_url: "https://formspree.io/f/xrgodpqo"
social_image: "./assets/img/social-link.jpg"
social_image_alt: # Alt text for the link preview image
google_analytics_measurement_id: # G-XXXXXXXXXX

sass:
  sass_dir: _sass

icon: ./assets/img/headshot.jpg
